export const ROOM_MESSAGE_EVENT = "m.room.message"
export const ROOM_REDACTION_EVENT = "m.room.redaction"
export const LOGIN_BY_PASSWORD = "m.login.password"
export const LOGIN_BY_TOKEN = "m.login.token"
export const DIRECT_EVENT = "m.direct"